<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><AssemblyName>GameLocalizer</AssemblyName><ApplicationIcon>Assets/GameLocalizer.ico</ApplicationIcon></PropertyGroup><ItemGroup><ProjectReference Include="../GameLocalizer.Infrastructure/GameLocalizer.Infrastructure.csproj"/><PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1"/><ProjectReference Include="../GameLocalizer.ModelHost/GameLocalizer.ModelHost.csproj" ReferenceOutputAssembly="false"/><ProjectReference Include="../GameLocalizer.Updater/GameLocalizer.Updater.csproj" ReferenceOutputAssembly="false"/></ItemGroup><ItemGroup><Resource Include="Assets/GameLocalizer.ico" /></ItemGroup></Project>
