using System.Text;
using System.Text.Json;
using GameLocalizer.Core.Localization;
using GameLocalizer.Core.Models;
using GameLocalizer.Infrastructure.FileSystem;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;
namespace GameLocalizer.Tests;
public sealed class ApplyDiagnosticsTests : IDisposable
{
    private readonly string root = Path.Combine(Path.GetTempPath(), "ApplyDiagnosticsTests", Guid.NewGuid().ToString("N"));
    private readonly BackupService backup;
    private readonly BepInExLocalizationAdapter adapter = new();
    private const string relative = "BepInEx/Translation/en/Text/dialogue.txt";
    public ApplyDiagnosticsTests() { Directory.CreateDirectory(root); backup = new(NullLogger<BackupService>.Instance, Path.Combine(root, "state")); }
    public void Dispose() => Directory.Delete(root, true);
    private string Write(string name, string text) { var path = Path.Combine(root, name); Directory.CreateDirectory(Path.GetDirectoryName(path)!); File.WriteAllText(path, text, new UTF8Encoding(true)); return path; }
    private async Task<FileChange> Change(string name = relative, string source = "ありがとう=Thank you.\r\n")
    {
        var path = Write(name, source); var snapshot = await TextFiles.ReadAsync(path, default);
        var values = adapter.Extract(source).ToDictionary(e => e.Id, _ => "Спасибо.");
        return new(name, snapshot.Hash, snapshot.Encode(adapter.ApplyTranslations(source, values))) { AdapterType = adapter.Name, LocalizationSlot = "en" };
    }
    [Fact] public async Task DiskRereadHashBackupParseAndReports()
    {
        var change = await Change(); await backup.ApplyAsync(root, [change], default);
        var report = Assert.IsType<ApplyDiagnosticReport>(backup.LastDiagnosticReport); var file = Assert.Single(report.Files);
        Assert.Equal("SUCCESS", report.Status); Assert.Equal("YES", file.SamePhysicalFile);
        Assert.NotEqual(file.BeforeHash, file.AfterHash); Assert.Equal(TextFiles.Hash(await File.ReadAllBytesAsync(file.PhysicalTargetFile)), file.AfterHash);
        Assert.True(file.ParseSuccess); Assert.True(file.BackupMatchesOriginal); Assert.Equal(change.ExpectedHash, file.BackupSHA256);
        var entry = Assert.Single(file.Entries); Assert.Equal("ありがとう", entry.Key); Assert.Equal("Спасибо.", entry.Actual); Assert.Equal("PASS", entry.ValidationStatus);
        Assert.Equal("EFBBBF", file.BOM); Assert.Equal("CRLF", file.LineEndings);
        Assert.True(File.Exists(backup.LastDiagnosticReportPath)); using var json = JsonDocument.Parse(await File.ReadAllTextAsync(Path.ChangeExtension(backup.LastDiagnosticReportPath, ".json")));
        Assert.Equal("SUCCESS", json.RootElement.GetProperty("Status").GetString());
    }
    [Theory] [InlineData("ru", "YES")] [InlineData("en", "NO")]
    public async Task ConfiguredPathResolutionMismatchAndNoConfigMutation(string language, string expected)
    {
        var change = await Change(); var config = Write("BepInEx/config/AutoTranslatorConfig.ini", $"[General]\nLanguage={language}\nFromLanguage=ja\n[Files]\nDirectory=Translation\\{{Lang}}\\Text\nOutputFile=_AutoGeneratedTranslations.txt");
        var bytes = File.ReadAllBytes(config); await backup.ApplyAsync(root, [change], default);
        Assert.Equal(expected, backup.LastDiagnosticReport!.ActiveLocalizationMismatch);
        Assert.Equal("UNKNOWN", backup.LastDiagnosticReport.ActiveLocalizationSource);
        Assert.Equal(bytes, File.ReadAllBytes(config)); Assert.False(Directory.Exists(Path.Combine(root, "BepInEx/Translation/ru")));
        Assert.Contains("FromLanguage", File.ReadAllText(backup.LastDiagnosticReportPath!));
    }
    [Fact] public async Task AlreadyAppliedOwnedContentIsVerifiedWithoutRewriting() {
        var change=await Change();await backup.ApplyAsync(root,[change],default);
        var target=Path.Combine(root,relative);var stamp=File.GetLastWriteTimeUtc(target);
        await backup.ApplyAsync(root,[change with {ExpectedHash=TextFiles.Hash(change.Content)}],default);
        Assert.Equal("SUCCESS",backup.LastDiagnosticReport!.Status);Assert.Equal("Completed",backup.LastDiagnosticReport.Stage);
        Assert.Equal(0,backup.LastDiagnosticReport.FilesActuallyChanged);Assert.Equal(stamp,File.GetLastWriteTimeUtc(target));
        Assert.True(backup.LastDiagnosticReport.Files.Single().BackupMatchesOriginal);Assert.Equal("PASS",backup.LastDiagnosticReport.Files.Single().Entries.Single().ValidationStatus);
    }
    [Fact] public async Task UnknownWithoutConfig() { await backup.ApplyAsync(root, [await Change()], default); Assert.Equal("UNKNOWN", backup.LastDiagnosticReport!.ActiveLocalizationMismatch); }
    [Fact] public async Task DuplicateAndOverrideValuesReported()
    {
        var change = await Change(); var competitor = Write("BepInEx/Translation/en/Text/other.txt", "ありがとう=Thank you.");
        await backup.ApplyAsync(root, [change], default); var entry = Assert.Single(Assert.Single(backup.LastDiagnosticReport!.Files).Entries);
        Assert.Equal("YES", entry.PotentialOverrideConflict); Assert.Single(entry.CompetingFiles); Assert.Equal(1, backup.LastDiagnosticReport.DuplicateKeyConflicts);
        var text = File.ReadAllText(backup.LastDiagnosticReportPath!); Assert.Contains("other.txt", text); Assert.Contains("Thank you.", text); Assert.Equal("ありがとう=Thank you.", File.ReadAllText(competitor));
    }
    [Fact] public async Task UnownedUnchangedContentFailsOwnershipAndGeneratesReport()
    {
        var change = await Change(); change = change with { Content = File.ReadAllBytes(Path.Combine(root, relative)) };
        await Assert.ThrowsAsync<IOException>(() => backup.ApplyAsync(root, [change], default)); Assert.Equal("FAILED", backup.LastDiagnosticReport!.Status);
        Assert.Contains("Ownership manifest missing", backup.LastDiagnosticReport.Error); Assert.True(File.Exists(backup.LastDiagnosticReportPath));
    }
    [Fact] public async Task MissingTargetFails() { var change = await Change(); File.Delete(Path.Combine(root, relative)); await Assert.ThrowsAsync<IOException>(() => backup.ApplyAsync(root, [change], default)); Assert.Equal("FAILED", backup.LastDiagnosticReport!.Status); }
    [Fact] public async Task CorruptBackupFails()
    {
        var change = await Change(); await backup.ApplyAsync(root, [change], default); File.WriteAllText(backup.LastDiagnosticReport!.Files[0].BackupPath, "corrupt");
        var snapshot = await TextFiles.ReadAsync(Path.Combine(root, relative), default);
        await Assert.ThrowsAsync<IOException>(() => backup.ApplyAsync(root, [change with { ExpectedHash = snapshot.Hash, Content = snapshot.Encode(snapshot.Text.Replace("Спасибо.", "Благодарю.")) }], default));
        Assert.False(backup.LastDiagnosticReport!.Files[0].BackupMatchesOriginal); Assert.Equal("FAILED", backup.LastDiagnosticReport.Status);
    }
    [Fact] public async Task PartialApplySummary()
    {
        var first = await Change(); var second = await Change("BepInEx/Translation/en/Text/second.txt");
        await backup.ApplyAsync(root, [second], default); File.WriteAllText(backup.LastDiagnosticReport!.Files[0].BackupPath, "corrupt");
        var snapshot = await TextFiles.ReadAsync(Path.Combine(root, second.RelativePath), default);
        second = second with { ExpectedHash = snapshot.Hash, Content = snapshot.Encode(snapshot.Text.Replace("Спасибо.", "Благодарю.")) };
        await Assert.ThrowsAsync<IOException>(() => backup.ApplyAsync(root, [first, second], default));
        Assert.Equal("PARTIAL", backup.LastDiagnosticReport!.Status); Assert.Equal(2, backup.LastDiagnosticReport.FilesExpectedToChange); Assert.Equal(1, backup.LastDiagnosticReport.FilesActuallyChanged);
    }
    [Fact] public async Task InvalidParserOutputDoesNotSucceed()
    {
        var path = Write("menu.json", "{\"text\":\"Hello\"}"); var change = new FileChange("menu.json", TextFiles.Hash(File.ReadAllBytes(path)), Encoding.UTF8.GetBytes("{invalid")) { AdapterType = "JSON" };
        await Assert.ThrowsAnyAsync<Exception>(() => backup.ApplyAsync(root, [change], default)); Assert.Equal("FAILED", backup.LastDiagnosticReport!.Status); Assert.Equal("{\"text\":\"Hello\"}", File.ReadAllText(path));
    }
}
